# API

Use ```get_arxiv_search_results(search_term)``` or ```get_pubmed_search_results(search_term)``` to get ```ArticleList```.

Use ```ArticleList.get_list_of(field)``` to get list of those fields.

## Common

#### Imports

In [10]:
import xml.etree.ElementTree as ET
import requests
import json
import datetime
import re
import pandas as pd

#### API URLs

In [11]:
API_PUBMED_PMCID = 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi'
API_PUBMED_SUMMARY = 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi'
API_ARXIV = 'https://export.arxiv.org/api/query'

#### Article class

In [12]:
class ArticleSummary(dict):
    def __init__(self, doi: str, id: str, title: str, pubdate: str, journal: str, authors: list[str], keywords: list[str], abstract: str):
        super().__init__(
            doi=doi,
            id=id,
            title=title,
            pubdate=pubdate,
            journal=journal,
            authors=authors,
            keywords=keywords,
            abstract=abstract
        )
        self.doi = doi
        self.id = id
        self.title = title
        self.pubdate = pubdate
        self.journal = journal
        self.authors = authors
        self.keywords = keywords
        self.abstract = abstract

#### Article List

In [13]:
class ArticleField:
    DOI = 'doi'
    ID = 'id'
    TITLE = 'title'
    PUBDATE = 'pubdate'
    JOURNAL = 'journal'
    AUTHORS = 'authors'
    KEYWORDS = 'keywords'
    ABSTRACT = 'abstract'

class ArticleList(list):
    def __init__(self, articles: list[ArticleSummary]):
        super().__init__(articles)
    
    def get_list_of(self, field: ArticleField) -> list:
        return [getattr(article, field) for article in self]

#### Requester

In [14]:
def request_with_retries(url, params, max_retries=3):
    for attempt in range(max_retries):
        try:
            response = requests.get(url, params=params)
            response.raise_for_status()
            return response
        except requests.RequestException as e:
            print(f'Attempt {attempt + 1} failed: {e}')
            if attempt == max_retries - 1:
                raise
    return None

## Searchers

### PubMed

In [15]:
def get_pmcids(search_term: str, max_results: int = 100) -> ArticleList:
    response = request_with_retries(
        url = API_PUBMED_PMCID,
        params = {
            'db': 'pubmed',
            'term': search_term,
            'retmax': max_results,
            'sort': 'relevance'
        }
    )

    if response is None:
        print('Failed to retrieve data after multiple attempts.')
        return []

    root = ET.fromstring(response.text)
    pmcids = root.findall('.//IdList/Id')

    return [pmcid.text for pmcid in pmcids]

def get_pubmed_search_results(search_term: str, max_results: int = 100) -> list[ArticleSummary]:
    pmcids = get_pmcids(search_term, max_results)
    response = request_with_retries(
        url = API_PUBMED_SUMMARY,
        params = {
            'id': ','.join(pmcids),
            'retmode': 'xml',
            'db': 'pubmed'
        }
    )

    if response is None:
        print('Failed to retrieve data after multiple attempts.')
        return []

    root = ET.fromstring(response.text)
    articles = root.findall('.//PubmedArticle')
    summaries = []
    for a in articles:
        doi = a.findtext('.//ArticleIdList/ArticleId[@IdType="doi"]') or ''
        id = a.findtext('.//MedlineCitation/PMID') or ''
        title = a.findtext('.//Article/ArticleTitle') or ''
        pubdate = a.findtext('.//Article/Journal/JournalIssue/PubDate/Year') or ''
        journal = a.findtext('.//Article/Journal/Title') or ''
        authors = [(author.findtext('LastName') or '') + ' ' + (author.findtext('ForeName') or '') for author in a.findall('.//Article/AuthorList/Author')]
        keywords = [kw.text for kw in a.findall('.//KeywordList/Keyword')]
        abstract = a.findtext('.//Article/Abstract/AbstractText') or ''
        summary = ArticleSummary(doi, id, title, pubdate, journal, authors, keywords, abstract)
        summaries.append(summary)

    return ArticleList(summaries)

In [16]:
pubmed_article_list = get_pubmed_search_results('cancer cells')
print(pubmed_article_list.get_list_of(ArticleField.TITLE))

json_summaries = json.dumps(pubmed_article_list)
with open('article_search_results_pubmed.json', 'w') as f:
    f.write(json_summaries)

df_pubmed = pd.DataFrame(pubmed_article_list)
df_pubmed

['Persistent Cancer Cells: The Deadly Survivors.', 'Polyploid giant cancer cells and cancer progression.', 'Cancer cells resist hyperthermia due to its obstructed activation of caspase 3.', 'Interconversion of Cancer Cells and Induced Pluripotent Stem Cells.', 'Cancer cells as a new source of induced pluripotent stem cells.', 'Infection of non-cancer cells: A barrier or support for oncolytic virotherapy?', 'Free cancer cells in gastric cancer - methods of detection, clinical and prognostic importance (meta-analysis).', 'The bacteria inside human cancer cells: Mainly as cancer promoters.', 'Effects of local anesthetics on cancer cells.', 'Lipid Metabolic Regulatory Crosstalk Between Cancer Cells and Tumor-Associated Macrophages.', 'Water Dynamics in Cancer Cells: Lessons from Quasielastic Neutron Scattering.', 'Are cancer cells really softer than normal cells?', 'Polyploid giant cancer cells: origin, possible pathways of formation, characteristics, and mechanisms of regulation.', 'Reprogramming cancer cells: overview & current progress.', 'Metabolic Crossroad Between Macrophages and Cancer Cells: Overview of Hepatocellular Carcinoma.', 'Role of neutrophils on cancer cells and other immune cells in the tumor microenvironment.', 'Stress-Induced Polyploid Giant Cancer Cells: Unique Way of Formation and Non-Negligible Characteristics.', 'Metabolic reprogramming for cancer cells and their microenvironment: Beyond the Warburg Effect.', 'Epithelial-Mesenchymal Transition Induced in Cancer Cells by Adhesion to Type I Collagen.', 'How Can We Treat Cancer Disease Not Cancer Cells?', 'Cancer cells optimize elasticity for efficient migration.', 'Proton pump inhibitors and sensitization of cancer cells to radiation therapy.', 'Electrical Impedance Spectroscopy for Monitoring Chemoresistance of Cancer Cells.', 'Three-Dimensional Culture System of Cancer Cells Combined with Biomaterials for Drug Screening.', 'Biological response of cancer cells to radiation treatment.', 'Generation of Cancer Stem Cells by Co-Culture Methods.', 'Role of glutamine and its metabolite ammonia in crosstalk of cancer-associated fibroblasts and cancer cells.', 'Phenotypic Plasticity of Cancer Cells Based on Remodeling of the Actin Cytoskeleton and Adhesive Structures.', 'Cancer cells arise from bacteria.', 'Bidirectional Interaction Between Cancer Cells and Platelets Provides Potential Strategies for Cancer Therapies.', 'Exosomal MicroRNAs as Mediators of Cellular Interactions Between Cancer Cells and Macrophages.', 'Metabolic Oscillations and Glycolytic Phenotypes of Cancer Cells.', 'Integrated regulation of chondrogenic differentiation in mesenchymal stem cells and differentiation of cancer cells.', 'Aldehyde Dehydrogenase-1A1 (ALDH1A1): The Novel Regulator of Chemoresistance in Pancreatic Cancer Cells.', 'Fer and FerT: A New Regulatory Link between Sperm and Cancer Cells.', 'Epigenetic regulation of autophagy: A key modification in cancer cells and cancer stem cells.', 'Cancer cells relax and resist cytotoxic attack.', 'The Warburg Effect on Cancer Cells Survival: The Role of Sugar Starvation in Cancer Therapy.', 'Effects of polystyrene nano- and microplastics on human breast epithelial cells and human breast cancer cells.', 'Concise Review: Crosstalk of Mesenchymal Stroma/Stem-Like Cells with Cancer Cells Provides Therapeutic Potential.', 'Collective Polarization of Cancer Cells at the Monolayer Boundary.', 'Autophagy Process in Trophoblast Cells Invasion and Differentiation: Similitude and Differences With Cancer Cells.', 'Advances and Challenges on Cancer Cells Reprogramming Using Induced Pluripotent Stem Cells Technologies.', 'Are polyploid giant cancer cells in high grade serous carcinoma of the ovary blastomere-like cancer stem cells?', 'Epigenetic and Pluripotency Aspects of Disseminated Cancer Cells During Minimal Residual Disease.', 'Cancer Cells Rely on Pain-Sensing Nerves in Nutrient-Scarce Conditions.', 'Intratumor Heterogeneity and Treatment Resistance of Solid Tumors with a Focus on Polyploid/Senescent Giant Cancer Cells (PGCCs).', 'Should EMT of Cancer Cells Be Understood as Epithelial-Myeloid Transition?', 'Cancer Cells Induce Delayed DNA Breaks to Resist Radiation Therapy.', 'Cross-talk between cancer-associated fibroblasts and dormant cancer cells: current status and promising therapeutic potential.', 'Polyploid Giant Cancer Cells (PGCCs): The Evil Roots of Cancer.', 'Dysregulation of Glucose Metabolism by Oncogenes and Tumor Suppressors in Cancer Cells.', 'Mechanical stress-induced cell death in breast cancer cells.', 'Oncogenes and tumor suppressors regulate glutamine metabolism in cancer cells.', 'Aberrant lipid metabolism in cancer cells and tumor microenvironment: the player rather than bystander in cancer progression and metastasis.', 'Advances in Screening and Development of Therapeutic Aptamers Against Cancer Cells.', 'Unravel the molecular mechanism of XBP1 in regulating the biology of cancer cells.', 'Metformin ameliorates BMP2 induced adipocyte-like property in breast cancer cells.', 'Autophagy-Deficient Pancreatic Cancer Cells Depend on Macropinocytosis.', 'Docosahexaenoic Acid Induces Oxidative DNA Damage and Apoptosis, and Enhances the Chemosensitivity of Cancer Cells.', 'Mitogenic effects of interleukin-8/CXCL8 on cancer cells.', 'Potential Roles of Acute Phase Proteins in Cancer: Why Do Cancer Cells Produce or Take Up Exogenous Acute Phase Protein Alpha1-Antitrypsin?', 'Nanoparticle Based Delivery of Protease Inhibitors to Cancer Cells.', 'Exploring the mechanical and electrical properties of cancer cells for improved diagnosis and treatment.', 'Cancer-Associated Fibroblasts Differentiated by Exosomes Isolated from Cancer Cells Promote Cancer Cell Invasion.', 'Molecular modulation of autophagy: New venture to target resistant cancer stem cells.', 'Mechanotransduction in Endothelial Cells in Vicinity of Cancer Cells.', 'Adhesion strength and anti-tumor agents regulate vinculin of breast cancer cells.', 'Human CD133-positive hematopoietic progenitor cells enhance the malignancy of breast cancer cells.', 'The Modified Phenanthridine PJ34 Unveils an Exclusive Cell-Death Mechanism in Human Cancer Cells.', 'Sensitization of Resistant Breast Cancer Cells with a Jumonji Family Histone Demethylase Inhibitor.', 'Quiescent Breast Cancer Cells Are Resistant to T-cell Killing.', 'Intraperitoneal free cancer cells in gastric cancer: pathology of peritoneal carcinomatosis and rationale for intraperitoneal chemotherapy/hyperthermic intraperitoneal chemotherapy in gastric cancer.', 'Addressing the Mechanical Interaction Between Cancer-Associated Fibroblasts and Cancer Cells by Laser Ablation.', 'A fluorescent probe for bioimaging of GSH in cancer cells.', 'Colorectal Cancer Cells Ectopically Express Hepcidin to Sequester Iron.', 'Label-Free Differentiation of Cancer and Non-Cancer Cells Based on Machine-Learning-Algorithm-Assisted Fast Raman Imaging.', 'A nucleolin-activated polyvalent aptamer nanoprobe for the detection of cancer cells.', 'RRBP1 depletion of bone metastatic cancer cells contributes to enhanced expression of the osteoblastic phenotype.', 'Methionine Restriction Increases Exosome Production and Secretion in Breast Cancer Cells.', 'Roles of lysophosphatidic acid (LPA) receptor-mediated signaling in cellular functions modulated by endothelial cells in pancreatic cancer cells under hypoxic conditions.', 'Aloperine Prevents Migration, Invasion, and Adhesion by Upregulating TIMP-4 in Human Bladder Cancer Cells.', 'Diverse effects of LPA receptors on cell motile activities of cancer cells.', 'Real-Time Stain-Free Classification of Cancer Cells and Blood Cells Using Interferometric Phase Microscopy and Machine Learning.', 'Endothelial transdifferentiation of human HGC-27 gastric cancer cells ', 'Thymopentin-Mediated Inhibition of Cancer Stem Cell Stemness Enhances the Cytotoxic Effect of Oxaliplatin on Colon Cancer Cells.', 'Autophagic Flux Assessment in Colorectal Cancer Cells.', 'Tuning the Cellular Uptake and Retention of Rhodamine Dyes by Molecular Engineering for High-Contrast Imaging of Cancer Cells.', 'Nuclear enlargement after confined migration in cancer cells.', 'Rapid establishment of highly migratory cells from cancer cells for investigating cellular functions.', 'Identification and Characterization of Tunneling Nanotubes Involved in Human Mast Cell FcεRI-Mediated Apoptosis of Cancer Cells.', 'Engineering Sandwiched Nanochannel Aptasensor for Efficiently Screening Cancer Cells.', 'Cancer cells in the circulating blood, with reference to cancer metastasis.', 'COVID-19, Flu May Reawaken Dormant Cancer Cells.', 'Statistical Analysis of Gastric Cancer Cells Response to Broadband Terahertz Radiation with and without Contrast Nanoparticles.', 'Increased Expression of NPM1 Suppresses p27', 'P2X7 receptor involved in antitumor activity of atractylenolide I in human cervical cancer cells.', 'Interaction between cancer cells and cancer-associated fibroblasts after cisplatin treatment promotes cancer cell regrowth.', 'RILP inhibits proliferation, migration, and invasion of PC3 prostate cancer cells.', 'Preparation and identification of anti-breast cancer cells peptides released from yak milk casein.']

,doi,id,title,pubdate,journal,authors,keywords,abstract
0,10.1016/j.cell.2020.10.027,33186528,Persistent Cancer Cells: The Deadly Survivors.,2020,Cell,"[Shen Shensi, Vagner Stéphan, Robert Caroline]","[adaptive resistance, cancer drug addiction, c...",Persistent cancer cells are the discrete and u...
1,10.3389/fcell.2022.1017588,36274852,Polyploid giant cancer cells and cancer progre...,2022,Frontiers in cell and developmental biology,"[Zhou Xinyue, Zhou Mingming, Zheng Minying, Ti...","[cancer stem cells, chemoradiotherapy resistan...",Polyploid giant cancer cells
2,10.1016/j.rpor.2020.02.008,32194353,Cancer cells resist hyperthermia due to its ob...,2020,Reports of practical oncology and radiotherapy...,"[Tang Xiaoren, Cao Feng, Ma Weiyuan, Tang Yini...",[Cancer cells resist hyperthermia],It is well known that inducing hyperthermia is...
3,10.3390/cells13020125,38247819,Interconversion of Cancer Cells and Induced Pl...,2024,Cells,"[Sarker Drishty B, Xue Yu, Mahmud Faiza, Jocel...","[cancer stem cell models, cancer stem cells, i...","Cancer cells, especially cancer stem cells (CS..."
4,10.1186/s13287-022-03145-y,36064437,Cancer cells as a new source of induced plurip...,2022,Stem cell research & therapy,"[Shamsian Azam, Sahebnasagh Roxana, Norouzy Am...","[Cancer cell reprogramming, Cancer-iPSCs, Indu...","Over the last 2 decades, induced pluripotent s..."
...,...,...,...,...,...,...,...,...
95,10.3390/cancers12102886,33050036,Increased Expression of NPM1 Suppresses p27,2020,Cancers,"[Kometani Tatsuya, Arai Takuya, Chibazakura Taku]","[CDK inhibitor, cancer cells, cell proliferati...",p27
96,10.1007/s11302-022-09854-6,35235139,P2X7 receptor involved in antitumor activity o...,2023,Purinergic signalling,"[Han Yue, Bai Can, He Xi-Meng, Ren Qing-Ling]","[Atractylenolide I, Hela cells, Human cervical...",Atractylenolide I (Atr-I) was found to sensiti...
97,10.1007/s13577-019-00275-z,31441010,Interaction between cancer cells and cancer-as...,2019,Human cell,"[Hisamitsu Shoshi, Miyashita Tomoyuki, Hashimo...","[Cancer-associated fibroblasts, Cisplatin, Lun...",Regrowth of cancer cells following chemotherap...
98,10.1016/j.acthis.2022.151938,35981451,"RILP inhibits proliferation, migration, and in...",2022,Acta histochemica,"[Wang Zhen, Zhou Yunhe, Nie Dongsong, Tan Yan,...","[Lysosome, PC3 prostate cancer cells, RILP, Ra...",RILP (Rab-interacting lysosomal protein) is a ...
99,10.3389/fnut.2022.997514,36091230,Preparation and identification of anti-breast ...,2022,Frontiers in nutrition,"[Gu Haofeng, Liang Lei, Zhu Ziwei, Mao Xueying]","[breast cancer cells, hydrolysate, identificat...",Yak milk casein (YMC) is the main protein in t...

### ArXiv

In [17]:
def get_arxiv_search_results(search_term: str, max_results: int = 100) -> ArticleList:
    response = request_with_retries(
        url = API_ARXIV,
        params = {
            'search_query': search_term,
            'start': 0,
            'max_results': max_results
        }
    )

    if response is None:
        print('Failed to retrieve data after multiple attempts.')
        return []

    root = ET.fromstring(response.text)
    ns = {
        "atom": "http://www.w3.org/2005/Atom",
        "arxiv": "http://arxiv.org/schemas/atom",
        "opensearch": "http://a9.com/-/spec/opensearch/1.1/",
    }
    entries = root.findall('atom:entry', ns)
    summaries = []
    for entry in entries:
        id = entry.findtext('atom:id', namespaces=ns)
        doi = entry.findtext('arxiv:doi', namespaces=ns)
        title = entry.findtext('atom:title', namespaces=ns)
        pubdate = datetime.datetime.strptime(entry.findtext('atom:published', namespaces=ns), '%Y-%m-%dT%H:%M:%S%z').strftime('%Y')
        journal = 'arXiv'
        authors = [author.findtext('atom:name', namespaces=ns) for author in entry.findall('atom:author', namespaces=ns)]
        keywords_text = entry.findtext('arxiv:comment', namespaces=ns)
        keywords_split = re.split(r'keywords:\s*', keywords_text, flags=re.IGNORECASE) if keywords_text else []
        if len(keywords_split) > 1:
            keywords = [kw.strip() for kw in keywords_split[1].split(',')]
        else:
            keywords = []
        abstract_element = entry.find('atom:summary', namespaces=ns)
        abstract = ''.join(abstract_element.itertext()).strip() if abstract_element is not None else ''
        summary = ArticleSummary(doi, id, title, pubdate, journal, authors, keywords, abstract)
        summaries.append(summary)

    return ArticleList(summaries)

In [18]:
arxiv_article_list = get_arxiv_search_results('UAV')
print(arxiv_article_list.get_list_of(ArticleField.TITLE))

json_arxiv_summaries = json.dumps(arxiv_article_list)
with open('article_search_results_arxiv.json', 'w') as f:
    f.write(json_arxiv_summaries)

df_arxiv = pd.DataFrame(arxiv_article_list)
df_arxiv

['UAV-VLRR: Vision-Language Informed NMPC for Rapid Response in UAV Search and Rescue', 'Capacity Characterization of UAV-Enabled Two-User Broadcast Channel', 'Repeatedly Energy-Efficient and Fair Service Coverage: UAV Slicing (Proactive UAV Network Slicing for URLLC and Mobile Broadband Service Multiplexing)', 'Common Throughput Maximization in UAV-Enabled OFDMA Systems with Delay Consideration', 'Hybrid Offline-Online Design for UAV-Enabled Data Harvesting in Probabilistic LoS Channel', 'Trajectory and Transmit Power Optimization for IRS-Assisted UAV Communication under Malicious Jamming', 'IRS-Aided Energy Efficient UAV Communication', 'Exploiting NOMA for Multi-Beam UAV Communication in Cellular Uplink', 'Robust Trajectory and Communication Design in IRS-Assisted UAV Communication under Malicious Jamming', 'The Design of Autonomous UAV Prototypes for Inspecting Tunnel Construction Environment', 'RIS-assisted UAV Communications for IoT with Wireless Power Transfer Using Deep Reinforcement Learning', 'An Experimental mmWave Channel Model for UAV-to-UAV Communications', 'Enabling UAV Cellular with Millimeter-Wave Communication: Potentials and Approaches', '3D UAV Trajectory and Data Collection Optimisation via Deep Reinforcement Learning', 'Resource Allocation for Solar Powered UAV Communication Systems', 'Joint Trajectory and Communication Design for Multi-UAV Enabled Wireless Networks', 'Joint Blocklength and Location Optimization for URLLC-enabled UAV Relay Systems', 'Detection and Classification of UAVs Using RF Fingerprints in the Presence of Interference', "Brain over Brawn: Using a Stereo Camera to Detect, Track, and Intercept a Faster UAV by Reconstructing the Intruder's Trajectory", 'UAV Trajectory and Communication Co-design: Flexible Path Discretization and Path Compression', 'UAV-Enabled Cooperative Jamming for Improving Secrecy of Ground Wiretap Channel', 'Fundamental Tradeoffs in Communication and Trajectory Design for UAV-Enabled Wireless Network', 'Physical Layer Security in UAV Systems: Challenges and Opportunities', 'Fusion of Cellular ISAC and Passive RF Sensing for UAV Detection and Tracking', "Advancing Experimental Platforms for UAV Communications: Insights from AERPAW'S Digital Twin", 'Speed-Aware Routing for UAV Ad-Hoc Networks', 'Enabling Smart Reflection in Integrated Air-Ground Wireless Network: IRS Meets UAV', 'Aerial-Ground Interference Mitigation for Cellular-Connected UAV', 'State Space System Modelling of a Quad Copter UAV', 'Energy Minimization in RIS-Assisted UAV-Enabled Wireless Power Transfer Systems', 'Combining LoRaWAN and a New 3D Motion Model for Remote UAV Tracking', 'On Greedy Routing in Dynamic UAV Networks', 'Energy Efficient Design in IRS-Assisted UAV Data Collection System under Malicious Jamming', 'Reconfigurable Intelligent Surface-assisted Multi-UAV Networks: Efficient Resource Allocation with Deep Reinforcement Learning', 'Ray Tracing Analysis for UAV-assisted Integrated Access and Backhaul Millimeter Wave Networks', 'The 3rd Anti-UAV Workshop & Challenge: Methods and Results', 'Multi-Modal UAV Detection, Classification and Tracking Algorithm -- Technical Report for CVPR 2024 UG2 Challenge', 'Safeguarding Wireless Network with UAVs: A Physical Layer Security Perspective', 'DroNet: Efficient convolutional neural network detector for real-time UAV applications', 'On the Energy Consumption of UAV Edge Computing in Non-Terrestrial Networks', 'Vision-only UAV State Estimation for Fast Flights Without External Localization Systems: A2RL Drone Racing Finalist Approach', 'SCOPE: A Training-Free Online 3D Deployment for UAV-BSs with Theoretical Analysis and Comparative Study', 'BAWSeg: A UAV Multispectral Benchmark for Barley Weed Segmentation', 'Securing the Skies: A Comprehensive Survey on Anti-UAV Methods, Benchmarking, and Future Directions', 'Energy Minimization for Active RIS-Aided UAV-Enabled SWIPT Systems', 'Energy-Efficient Cyclical Trajectory Design for UAV-Aided Maritime Data Collection in Wind', 'Distributed Intelligent System Architecture for UAV-Assisted Monitoring of Wind Energy Infrastructure', 'A Decision-theoretic Approach to Detection-based Target Search with a UAV', 'Evolutionary Biparty Multiobjective UAV Path Planning: Problems and Empirical Comparisons', 'Sea You Later: Metadata-Guided Long-Term Re-Identification for UAV-Based Multi-Object Tracking', 'Two-Tier UAV-based Low Power Wide Area Networks: A Testbed and Experimentation Study', 'Integration of the 3D Environment for UAV Onboard Visual Object Tracking', 'Weighted strategies to guide a multi-objective evolutionary algorithm for multi-UAV mission planning', 'Resilient Topology-Aware Coordination for Dynamic 3D UAV Networks under Node Failure', 'Cellular UAV-to-UAV Communications', 'Cellular UAV-to-X Communications: Design and Optimization for Multi-UAV Networks', 'UAV Deployment Optimization in UAV-assisted Wireless Communications', 'Energy-Efficient UAV Replacement in Software-Defined UAV Networks', 'Defending against Intrusion of Malicious UAVs with Networked UAV Defense Swarms', 'Robust Resource Allocation for UAV Systems with UAV Jittering and User Location Uncertainty', 'Collaborative Reinforcement Learning Based Unmanned Aerial Vehicle (UAV) Trajectory Design for 3D UAV Tracking', 'UAV-GESTURE: A Dataset for UAV Control and Gesture Recognition', 'Towards Robust UAV Tracking in GNSS-Denied Environments: A Multi-LiDAR Multi-UAV Dataset', 'Hierarchical Learning Framework for UAV Detection and Identification', 'Thermal RGB Fusion for Micro-UAV Wildfire Perimeter Tracking with Minimal Comms', 'UAV-Assisted Image Acquisition: 3D UAV Trajectory Design and Camera Control', 'UAV-VisLoc: A Large-scale Dataset for UAV Visual Localization', 'A Survey of Channel Modeling for UAV Communications', 'MOR-UAV: A Benchmark Dataset and Baselines for Moving Object Recognition in UAV Videos', 'CST Anti-UAV: A Thermal Infrared Benchmark for Tiny UAV Tracking in Complex Scenes', 'A Survey of Prototype and Experiment for UAV Communications', 'Power-Efficient Deployment of UAVs as Relays', 'UAV-Rain1k: A Benchmark for Raindrop Removal from UAV Aerial Imagery', 'Optimal UAV Hitching on Ground Vehicles', 'Autonomous UAV Navigation Using Reinforcement Learning', 'Benchmarking the Robustness of UAV Tracking Against Common Corruptions', 'Swarm UAVs Communication', 'Implementation of UAV Coordination Based on a Hierarchical Multi-UAV Simulation Platform', 'BRM Localization: UAV Localization in GNSS-Denied Environments Based on Matching of Numerical Map and UAV Images', 'Generative AI for Advanced UAV Networking', 'Blockchain-Based Identity Authentication Oriented to Multi-Cluster UAV Networking', 'Access Points in the Air: Modeling and Optimization of Fixed-Wing UAV Network', 'Robust and Decentralized Reinforcement Learning for UAV Path Planning in IoT Networks', 'Anti-UAV: A Large Multi-Modal Benchmark for UAV Tracking', 'Throughput Maximization of UAV Networks', 'Semi-supervised Learning Framework for UAV Detection', 'Stag hunt game-based approach for cooperative UAVs', 'UAV-SEAD: State Estimation Anomaly Dataset for UAVs', 'A Survey on Millimeter-Wave Beamforming Enabled UAV Communications and Networking', 'Learning with Dynamics: Autonomous Regulation of UAV Based Communication Networks with Dynamic UAV Crew', 'Design and Implementation of Emergency Simulated Lighting System Based on Tello UAV', 'Optimal Placement of UAVs for Minimum Outage Probability', 'Throughput of Hybrid UAV Networks with Scale-Free Topology', 'Connectivity and Collision Constrained Opportunistic Routing for Emergency Communication using UAV', 'UAV-Flow Colosseo: A Real-World Benchmark for Flying-on-a-Word UAV Imitation Learning', 'Energy Efficiency Maximization for Full-Duplex UAV Secrecy Communication', 'Sensing and Communication Tradeoff Design for AoI Minimization in a Cellular Internet of UAVs', 'Rank-Based Filter Pruning for Real-Time UAV Tracking', 'UAV (Unmanned Aerial Vehicles): Diverse Applications of UAV Datasets in Segmentation, Classification, Detection, and Tracking', 'Survey of Important Issues in UAV Communication Networks']

,doi,id,title,pubdate,journal,authors,keywords,abstract
0,NaN,http://arxiv.org/abs/2503.02465v2,UAV-VLRR: Vision-Language Informed NMPC for Ra...,2025,arXiv,"[Yasheerah Yaqoot, Muhammad Ahsan Mustafa, Ole...",[],Emergency search and rescue (SAR) operations o...
1,NaN,http://arxiv.org/abs/1801.00443v2,Capacity Characterization of UAV-Enabled Two-U...,2018,arXiv,"[Qingqing Wu, Jie Xu, Rui Zhang]",[],Although prior works have exploited the UAV's ...
2,NaN,http://arxiv.org/abs/1912.03600v5,Repeatedly Energy-Efficient and Fair Service C...,2019,arXiv,"[Peng Yang, Xing Xi, Tony Q. S. Quek, Jingxuan...",[],Unmanned aerial vehicle (UAV) networks are con...
3,NaN,http://arxiv.org/abs/1801.00444v2,Common Throughput Maximization in UAV-Enabled ...,2018,arXiv,"[Qingqing Wu, Rui Zhang]",[],The use of unmanned aerial vehicles (UAVs) as ...
4,NaN,http://arxiv.org/abs/1907.06181v2,Hybrid Offline-Online Design for UAV-Enabled D...,2019,arXiv,"[Changsheng You, Rui Zhang]",[],This paper considers an unmanned aerial vehicl...
...,...,...,...,...,...,...,...,...
95,NaN,http://arxiv.org/abs/1906.07346v1,Energy Efficiency Maximization for Full-Duplex...,2019,arXiv,"[Bin Duo, Qingqing Wu, Xiaojun Yuan, Rui Zhang]",[],This letter proposes a new full-duplex (FD) se...
96,NaN,http://arxiv.org/abs/2002.00146v1,Sensing and Communication Tradeoff Design for ...,2020,arXiv,"[Shuhang Zhang, Hongliang Zhang, Lingyang Song...",[],"In this paper, we consider the cellular Intern..."
97,NaN,http://arxiv.org/abs/2207.01768v1,Rank-Based Filter Pruning for Real-Time UAV Tr...,2022,arXiv,"[Xucheng Wang, Dan Zeng, Qijun Zhao, Shuiwang Li]",[],Unmanned aerial vehicle (UAV) tracking has wid...
98,NaN,http://arxiv.org/abs/2409.03245v1,UAV (Unmanned Aerial Vehicles): Diverse Applic...,2024,arXiv,"[Md. Mahfuzur Rahman, Sunzida Siddique, Marufa...",[],"Unmanned Aerial Vehicles (UAVs), have greatly ..."
99,10.1109/COMST.2015.2495297,http://arxiv.org/abs/1603.08462v1,Survey of Important Issues in UAV Communicatio...,2016,arXiv,"[Lav Gupta, Raj Jain, Gabor Vaszkun]",[],Unmanned Aerial Vehicles (UAVs) have enormous ...